USE [AzuroSMS]
GO

/****** Object:  StoredProcedure [dbo].[UpdateSmsSendLog]    Script Date: 05/26/2012 01:38:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- Author:        JohannU
-- From:          MEDIVH
-- Generated by:  Data Entity Generator (1.1.1.0)
-- Create date:   2012/03/15
-- Description:   Update procedure for SmsSendLog
-- =============================================

CREATE procedure [dbo].[UpdateSmsSendLog]
(
	@ID bigint,
	@OrganizationId uniqueidentifier,
	@ActivityId uniqueidentifier,
	@MobileNumber nvarchar (20),
	@DateSent datetime,
	@DateDelivered datetime,
	@Provider nvarchar (50),
	@ProviderId nvarchar (50),
	@ProviderStatus nvarchar (10),
	@ProviderStatusMessage nvarchar (100),
	@Message nvarchar(500)
)
as

-- Do the Update
update
	[dbo].[SmsSendLog]
set
	[OrganizationId] = @OrganizationId,
	[ActivityId] = @ActivityId,
	[MobileNumber] = @MobileNumber,
	[DateSent] = @DateSent,
	[DateDelivered] = @DateDelivered,
	[Provider] = @Provider,
	[ProviderId] = @ProviderId,
	[ProviderStatus] = @ProviderStatus,
	[ProviderStatusMessage] = @ProviderStatusMessage,
	[Message] = @Message,
	[DateChanged] = GETDATE()
where
	[ID] = @ID
GO


