//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azuro.Crm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public enum msdyn_responseactionState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Actions that can occur when the respondent enters a response.  Actions can be server side or client side.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_responseaction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public partial class msdyn_responseaction : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string EmailAddress = "emailaddress";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string msdyn_Action = "msdyn_action";
			public const string msdyn_ChainDestinationSurvey = "msdyn_chaindestinationsurvey";
			public const string msdyn_ChainSurveyUniqueidentifier = "msdyn_chainsurveyuniqueidentifier";
			public const string msdyn_Description = "msdyn_description";
			public const string msdyn_Grid = "msdyn_grid";
			public const string msdyn_name = "msdyn_name";
			public const string msdyn_OrderIndex = "msdyn_orderindex";
			public const string msdyn_Page = "msdyn_page";
			public const string msdyn_Question = "msdyn_question";
			public const string msdyn_Queuetonotify = "msdyn_queuetonotify";
			public const string msdyn_responseactionId = "msdyn_responseactionid";
			public const string Id = "msdyn_responseactionid";
			public const string msdyn_responseoutcomeType = "msdyn_responseoutcometype";
			public const string msdyn_Scope = "msdyn_scope";
			public const string msdyn_Section = "msdyn_section";
			public const string msdyn_SenderUser = "msdyn_senderuser";
			public const string msdyn_Survey = "msdyn_survey";
			public const string msdyn_Teamtonotify = "msdyn_teamtonotify";
			public const string msdyn_Usertonotify = "msdyn_usertonotify";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string msdyn_msdyn_question_msdyn_responseaction_Question = "msdyn_msdyn_question_msdyn_responseaction_Question";
			public const string msdyn_msdyn_survey_msdyn_responseaction_ChainDestinationSurvey = "msdyn_msdyn_survey_msdyn_responseaction_ChainDestinationSurvey";
			public const string msdyn_page_msdyn_responseaction_Page = "msdyn_page_msdyn_responseaction_Page";
			public const string msdyn_questiongroup_msdyn_responseaction_Grid = "msdyn_questiongroup_msdyn_responseaction_Grid";
			public const string msdyn_section_msdyn_responseaction_Section = "msdyn_section_msdyn_responseaction_Section";
			public const string msdyn_survey_msdyn_responseaction_Survey = "msdyn_survey_msdyn_responseaction_Survey";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public msdyn_responseaction() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "msdyn_responseaction";
		
		public const string PrimaryIdAttribute = "msdyn_responseactionid";
		
		public const string PrimaryNameAttribute = "msdyn_name";
		
		public const int EntityTypeCode = 10020;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// The primary email address for the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailaddress")]
		public string EmailAddress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("emailaddress");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("EmailAddress");
				this.SetAttributeValue("emailaddress", value);
				this.OnPropertyChanged("EmailAddress");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Select the actions that can occur when the respondent enters a response.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_action")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_Action
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_action");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Action");
				this.SetAttributeValue("msdyn_action", value);
				this.OnPropertyChanged("msdyn_Action");
			}
		}
		
		/// <summary>
		/// Enter the chain destination survey.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_chaindestinationsurvey")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_ChainDestinationSurvey
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_chaindestinationsurvey");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ChainDestinationSurvey");
				this.SetAttributeValue("msdyn_chaindestinationsurvey", value);
				this.OnPropertyChanged("msdyn_ChainDestinationSurvey");
			}
		}
		
		/// <summary>
		/// Shows chain destination survey
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_chainsurveyuniqueidentifier")]
		public string msdyn_ChainSurveyUniqueidentifier
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_chainsurveyuniqueidentifier");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ChainSurveyUniqueidentifier");
				this.SetAttributeValue("msdyn_chainsurveyuniqueidentifier", value);
				this.OnPropertyChanged("msdyn_ChainSurveyUniqueidentifier");
			}
		}
		
		/// <summary>
		/// Type a description for the response action.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_description")]
		public string msdyn_Description
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_description");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Description");
				this.SetAttributeValue("msdyn_description", value);
				this.OnPropertyChanged("msdyn_Description");
			}
		}
		
		/// <summary>
		/// Enter the grid.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_grid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Grid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_grid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Grid");
				this.SetAttributeValue("msdyn_grid", value);
				this.OnPropertyChanged("msdyn_Grid");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_name")]
		public string msdyn_name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_name");
				this.SetAttributeValue("msdyn_name", value);
				this.OnPropertyChanged("msdyn_name");
			}
		}
		
		/// <summary>
		/// Set the order of precedence for the response action.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_orderindex")]
		public System.Nullable<int> msdyn_OrderIndex
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyn_orderindex");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_OrderIndex");
				this.SetAttributeValue("msdyn_orderindex", value);
				this.OnPropertyChanged("msdyn_OrderIndex");
			}
		}
		
		/// <summary>
		/// Enter the page.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_page")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Page
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_page");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Page");
				this.SetAttributeValue("msdyn_page", value);
				this.OnPropertyChanged("msdyn_Page");
			}
		}
		
		/// <summary>
		/// Enter the question.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_question")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Question
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_question");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Question");
				this.SetAttributeValue("msdyn_question", value);
				this.OnPropertyChanged("msdyn_Question");
			}
		}
		
		/// <summary>
		/// Shows the queue associated with the response outcome rule.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_queuetonotify")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Queuetonotify
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_queuetonotify");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Queuetonotify");
				this.SetAttributeValue("msdyn_queuetonotify", value);
				this.OnPropertyChanged("msdyn_Queuetonotify");
			}
		}
		
		/// <summary>
		/// Shows the entity instances.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_responseactionid")]
		public System.Nullable<System.Guid> msdyn_responseactionId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_responseactionid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_responseactionId");
				this.SetAttributeValue("msdyn_responseactionid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("msdyn_responseactionId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_responseactionid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.msdyn_responseactionId = value;
			}
		}
		
		/// <summary>
		/// Select the type of response outcome.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_responseoutcometype")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_responseoutcomeType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_responseoutcometype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_responseoutcomeType");
				this.SetAttributeValue("msdyn_responseoutcometype", value);
				this.OnPropertyChanged("msdyn_responseoutcomeType");
			}
		}
		
		/// <summary>
		/// Select the client or server response action.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_scope")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_Scope
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_scope");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Scope");
				this.SetAttributeValue("msdyn_scope", value);
				this.OnPropertyChanged("msdyn_Scope");
			}
		}
		
		/// <summary>
		/// Enter the section.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_section")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Section
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_section");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Section");
				this.SetAttributeValue("msdyn_section", value);
				this.OnPropertyChanged("msdyn_Section");
			}
		}
		
		/// <summary>
		/// Shows User associated with Response Outcome Rule.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_senderuser")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_SenderUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_senderuser");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_SenderUser");
				this.SetAttributeValue("msdyn_senderuser", value);
				this.OnPropertyChanged("msdyn_SenderUser");
			}
		}
		
		/// <summary>
		/// Enter the survey.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_survey")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Survey
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_survey");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Survey");
				this.SetAttributeValue("msdyn_survey", value);
				this.OnPropertyChanged("msdyn_Survey");
			}
		}
		
		/// <summary>
		/// Shows the team associated with the response outcome rule.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_teamtonotify")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Teamtonotify
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_teamtonotify");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Teamtonotify");
				this.SetAttributeValue("msdyn_teamtonotify", value);
				this.OnPropertyChanged("msdyn_Teamtonotify");
			}
		}
		
		/// <summary>
		/// Shows the user associated with the response outcome rule.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_usertonotify")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Usertonotify
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_usertonotify");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Usertonotify");
				this.SetAttributeValue("msdyn_usertonotify", value);
				this.OnPropertyChanged("msdyn_Usertonotify");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Response Action
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Azuro.Crm.Entities.msdyn_responseactionState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Azuro.Crm.Entities.msdyn_responseactionState)(System.Enum.ToObject(typeof(Azuro.Crm.Entities.msdyn_responseactionState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Response Action
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule")]
		public System.Collections.Generic.IEnumerable<Azuro.Crm.Entities.msdyn_responseoutcome> msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Azuro.Crm.Entities.msdyn_responseoutcome>("msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule");
				this.SetRelatedEntities<Azuro.Crm.Entities.msdyn_responseoutcome>("msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule", null, value);
				this.OnPropertyChanged("msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_responseaction_ActivityParties
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_responseaction_ActivityParties")]
		public System.Collections.Generic.IEnumerable<Azuro.Crm.Entities.ActivityParty> msdyn_responseaction_ActivityParties
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Azuro.Crm.Entities.ActivityParty>("msdyn_responseaction_ActivityParties", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_responseaction_ActivityParties");
				this.SetRelatedEntities<Azuro.Crm.Entities.ActivityParty>("msdyn_responseaction_ActivityParties", null, value);
				this.OnPropertyChanged("msdyn_responseaction_ActivityParties");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_responseaction_ActivityPointers
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_responseaction_ActivityPointers")]
		public System.Collections.Generic.IEnumerable<Azuro.Crm.Entities.ActivityPointer> msdyn_responseaction_ActivityPointers
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Azuro.Crm.Entities.ActivityPointer>("msdyn_responseaction_ActivityPointers", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_responseaction_ActivityPointers");
				this.SetRelatedEntities<Azuro.Crm.Entities.ActivityPointer>("msdyn_responseaction_ActivityPointers", null, value);
				this.OnPropertyChanged("msdyn_responseaction_ActivityPointers");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_responseaction_cdi_txtmessages
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_responseaction_cdi_txtmessages")]
		public System.Collections.Generic.IEnumerable<Azuro.Crm.Entities.cdi_txtmessage> msdyn_responseaction_cdi_txtmessages
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Azuro.Crm.Entities.cdi_txtmessage>("msdyn_responseaction_cdi_txtmessages", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_responseaction_cdi_txtmessages");
				this.SetRelatedEntities<Azuro.Crm.Entities.cdi_txtmessage>("msdyn_responseaction_cdi_txtmessages", null, value);
				this.OnPropertyChanged("msdyn_responseaction_cdi_txtmessages");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_responseaction_msdyn_surveyinvites
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_responseaction_msdyn_surveyinvites")]
		public System.Collections.Generic.IEnumerable<Azuro.Crm.Entities.msdyn_surveyinvite> msdyn_responseaction_msdyn_surveyinvites
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Azuro.Crm.Entities.msdyn_surveyinvite>("msdyn_responseaction_msdyn_surveyinvites", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_responseaction_msdyn_surveyinvites");
				this.SetRelatedEntities<Azuro.Crm.Entities.msdyn_surveyinvite>("msdyn_responseaction_msdyn_surveyinvites", null, value);
				this.OnPropertyChanged("msdyn_responseaction_msdyn_surveyinvites");
			}
		}
		
		/// <summary>
		/// N:N msdyn_responserouting_msdyn_responseaction
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_responserouting_msdyn_responseaction")]
		public System.Collections.Generic.IEnumerable<Azuro.Crm.Entities.msdyn_responserouting> msdyn_responserouting_msdyn_responseaction
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Azuro.Crm.Entities.msdyn_responserouting>("msdyn_responserouting_msdyn_responseaction", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_responserouting_msdyn_responseaction");
				this.SetRelatedEntities<Azuro.Crm.Entities.msdyn_responserouting>("msdyn_responserouting_msdyn_responseaction", null, value);
				this.OnPropertyChanged("msdyn_responserouting_msdyn_responseaction");
			}
		}
		
		/// <summary>
		/// N:N msdyn_responserouting_responseaction_else
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_responserouting_responseaction_else")]
		public System.Collections.Generic.IEnumerable<Azuro.Crm.Entities.msdyn_responserouting> msdyn_responserouting_responseaction_else
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Azuro.Crm.Entities.msdyn_responserouting>("msdyn_responserouting_responseaction_else", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_responserouting_responseaction_else");
				this.SetRelatedEntities<Azuro.Crm.Entities.msdyn_responserouting>("msdyn_responserouting_responseaction_else", null, value);
				this.OnPropertyChanged("msdyn_responserouting_responseaction_else");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_question_msdyn_responseaction_Question
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_question")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_question_msdyn_responseaction_Question")]
		public Azuro.Crm.Entities.msdyn_question msdyn_msdyn_question_msdyn_responseaction_Question
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.msdyn_question>("msdyn_msdyn_question_msdyn_responseaction_Question", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_question_msdyn_responseaction_Question");
				this.SetRelatedEntity<Azuro.Crm.Entities.msdyn_question>("msdyn_msdyn_question_msdyn_responseaction_Question", null, value);
				this.OnPropertyChanged("msdyn_msdyn_question_msdyn_responseaction_Question");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_survey_msdyn_responseaction_ChainDestinationSurvey
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_chaindestinationsurvey")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_survey_msdyn_responseaction_ChainDestinationSurvey")]
		public Azuro.Crm.Entities.msdyn_survey msdyn_msdyn_survey_msdyn_responseaction_ChainDestinationSurvey
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.msdyn_survey>("msdyn_msdyn_survey_msdyn_responseaction_ChainDestinationSurvey", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_survey_msdyn_responseaction_ChainDestinationSurvey");
				this.SetRelatedEntity<Azuro.Crm.Entities.msdyn_survey>("msdyn_msdyn_survey_msdyn_responseaction_ChainDestinationSurvey", null, value);
				this.OnPropertyChanged("msdyn_msdyn_survey_msdyn_responseaction_ChainDestinationSurvey");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_page_msdyn_responseaction_Page
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_page")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_page_msdyn_responseaction_Page")]
		public Azuro.Crm.Entities.msdyn_page msdyn_page_msdyn_responseaction_Page
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.msdyn_page>("msdyn_page_msdyn_responseaction_Page", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_page_msdyn_responseaction_Page");
				this.SetRelatedEntity<Azuro.Crm.Entities.msdyn_page>("msdyn_page_msdyn_responseaction_Page", null, value);
				this.OnPropertyChanged("msdyn_page_msdyn_responseaction_Page");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_questiongroup_msdyn_responseaction_Grid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_grid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_questiongroup_msdyn_responseaction_Grid")]
		public Azuro.Crm.Entities.msdyn_questiongroup msdyn_questiongroup_msdyn_responseaction_Grid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.msdyn_questiongroup>("msdyn_questiongroup_msdyn_responseaction_Grid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_questiongroup_msdyn_responseaction_Grid");
				this.SetRelatedEntity<Azuro.Crm.Entities.msdyn_questiongroup>("msdyn_questiongroup_msdyn_responseaction_Grid", null, value);
				this.OnPropertyChanged("msdyn_questiongroup_msdyn_responseaction_Grid");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_section_msdyn_responseaction_Section
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_section")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_section_msdyn_responseaction_Section")]
		public Azuro.Crm.Entities.msdyn_section msdyn_section_msdyn_responseaction_Section
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.msdyn_section>("msdyn_section_msdyn_responseaction_Section", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_section_msdyn_responseaction_Section");
				this.SetRelatedEntity<Azuro.Crm.Entities.msdyn_section>("msdyn_section_msdyn_responseaction_Section", null, value);
				this.OnPropertyChanged("msdyn_section_msdyn_responseaction_Section");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_survey_msdyn_responseaction_Survey
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_survey")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_survey_msdyn_responseaction_Survey")]
		public Azuro.Crm.Entities.msdyn_survey msdyn_survey_msdyn_responseaction_Survey
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.msdyn_survey>("msdyn_survey_msdyn_responseaction_Survey", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_survey_msdyn_responseaction_Survey");
				this.SetRelatedEntity<Azuro.Crm.Entities.msdyn_survey>("msdyn_survey_msdyn_responseaction_Survey", null, value);
				this.OnPropertyChanged("msdyn_survey_msdyn_responseaction_Survey");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public msdyn_responseaction(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["msdyn_responseactionid"] = base.Id;
                        break;
                    case "msdyn_responseactionid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_action")]
		public virtual msdyn_responseaction_msdyn_Action? msdyn_ActionEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_responseaction_msdyn_Action?)(EntityOptionSetEnum.GetEnum(this, "msdyn_action")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				msdyn_Action = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_responseoutcometype")]
		public virtual msdyn_SurveyActionType? msdyn_responseoutcomeTypeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_SurveyActionType?)(EntityOptionSetEnum.GetEnum(this, "msdyn_responseoutcometype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				msdyn_responseoutcomeType = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_scope")]
		public virtual msdyn_responseaction_msdyn_Scope? msdyn_ScopeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_responseaction_msdyn_Scope?)(EntityOptionSetEnum.GetEnum(this, "msdyn_scope")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				msdyn_Scope = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual msdyn_responseaction_StatusCode? StatusCodeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_responseaction_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				StatusCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}