//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azuro.Crm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public enum msdyn_responseoutcomeState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Information about the response that will trigger a workflow to run business logic. This is created as the output of the response action.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_responseoutcome")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public partial class msdyn_responseoutcome : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string msdyn_Account = "msdyn_account";
			public const string msdyn_Contact = "msdyn_contact";
			public const string msdyn_Invitation = "msdyn_invitation";
			public const string msdyn_Lead = "msdyn_lead";
			public const string msdyn_name = "msdyn_name";
			public const string msdyn_responseoutcomeId = "msdyn_responseoutcomeid";
			public const string Id = "msdyn_responseoutcomeid";
			public const string msdyn_responseoutcomeType = "msdyn_responseoutcometype";
			public const string msdyn_SurveyId = "msdyn_surveyid";
			public const string msdyn_SurveyResponse = "msdyn_surveyresponse";
			public const string msdyn_TriggeringResponseActionRule = "msdyn_triggeringresponseactionrule";
			public const string msdyn_TriggeringResponseText = "msdyn_triggeringresponsetext";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string msdyn_account_msdyn_responseoutcome_Account = "msdyn_account_msdyn_responseoutcome_Account";
			public const string msdyn_contact_msdyn_responseoutcome_Contact = "msdyn_contact_msdyn_responseoutcome_Contact";
			public const string msdyn_lead_msdyn_responseoutcome_Lead = "msdyn_lead_msdyn_responseoutcome_Lead";
			public const string msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule = "msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule";
			public const string msdyn_msdyn_survey_msdyn_responseoutcome_SurveyId = "msdyn_msdyn_survey_msdyn_responseoutcome_SurveyId";
			public const string msdyn_msdyn_surveyinvite_msdyn_responseoutcome_Invitation = "msdyn_msdyn_surveyinvite_msdyn_responseoutcome_Invitation";
			public const string msdyn_surveyresponse_SurveyResponse = "msdyn_surveyresponse_SurveyResponse";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public msdyn_responseoutcome() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "msdyn_responseoutcome";
		
		public const string PrimaryIdAttribute = "msdyn_responseoutcomeid";
		
		public const string PrimaryNameAttribute = "msdyn_name";
		
		public const int EntityTypeCode = 10022;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Shows the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Shows the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Shows the sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Shows the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Shows the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Shows the account associated with the action.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_account")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Account
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_account");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Account");
				this.SetAttributeValue("msdyn_account", value);
				this.OnPropertyChanged("msdyn_Account");
			}
		}
		
		/// <summary>
		/// Shows Contact associated with Action.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_contact")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Contact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_contact");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Contact");
				this.SetAttributeValue("msdyn_contact", value);
				this.OnPropertyChanged("msdyn_Contact");
			}
		}
		
		/// <summary>
		/// Shows Survey Activity associated with Action.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_invitation")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Invitation
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_invitation");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Invitation");
				this.SetAttributeValue("msdyn_invitation", value);
				this.OnPropertyChanged("msdyn_Invitation");
			}
		}
		
		/// <summary>
		/// Shows Lead associated with Action.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_lead")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Lead
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_lead");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Lead");
				this.SetAttributeValue("msdyn_lead", value);
				this.OnPropertyChanged("msdyn_Lead");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_name")]
		public string msdyn_name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_name");
				this.SetAttributeValue("msdyn_name", value);
				this.OnPropertyChanged("msdyn_name");
			}
		}
		
		/// <summary>
		/// Shows the entity instances.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_responseoutcomeid")]
		public System.Nullable<System.Guid> msdyn_responseoutcomeId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_responseoutcomeid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_responseoutcomeId");
				this.SetAttributeValue("msdyn_responseoutcomeid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("msdyn_responseoutcomeId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_responseoutcomeid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.msdyn_responseoutcomeId = value;
			}
		}
		
		/// <summary>
		/// Select the response outcome type.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_responseoutcometype")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_responseoutcomeType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_responseoutcometype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_responseoutcomeType");
				this.SetAttributeValue("msdyn_responseoutcometype", value);
				this.OnPropertyChanged("msdyn_responseoutcomeType");
			}
		}
		
		/// <summary>
		/// Shows Survey associated with Action.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_surveyid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_SurveyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_surveyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_SurveyId");
				this.SetAttributeValue("msdyn_surveyid", value);
				this.OnPropertyChanged("msdyn_SurveyId");
			}
		}
		
		/// <summary>
		/// Shows Survey Response associated with Action.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_surveyresponse")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_SurveyResponse
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_surveyresponse");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_SurveyResponse");
				this.SetAttributeValue("msdyn_surveyresponse", value);
				this.OnPropertyChanged("msdyn_SurveyResponse");
			}
		}
		
		/// <summary>
		/// Shows Response Outcome Rule associated with Response Outcome.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_triggeringresponseactionrule")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_TriggeringResponseActionRule
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_triggeringresponseactionrule");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TriggeringResponseActionRule");
				this.SetAttributeValue("msdyn_triggeringresponseactionrule", value);
				this.OnPropertyChanged("msdyn_TriggeringResponseActionRule");
			}
		}
		
		/// <summary>
		/// Select the text that will trigger a response.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_triggeringresponsetext")]
		public string msdyn_TriggeringResponseText
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_triggeringresponsetext");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TriggeringResponseText");
				this.SetAttributeValue("msdyn_triggeringresponsetext", value);
				this.OnPropertyChanged("msdyn_TriggeringResponseText");
			}
		}
		
		/// <summary>
		/// Shows the date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Shows the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Shows the status of the action.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Azuro.Crm.Entities.msdyn_responseoutcomeState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Azuro.Crm.Entities.msdyn_responseoutcomeState)(System.Enum.ToObject(typeof(Azuro.Crm.Entities.msdyn_responseoutcomeState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Shows the reason for the status of the action.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Shows the time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_account_msdyn_responseoutcome_Account
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_account")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_account_msdyn_responseoutcome_Account")]
		public Azuro.Crm.Entities.Account msdyn_account_msdyn_responseoutcome_Account
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.Account>("msdyn_account_msdyn_responseoutcome_Account", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_account_msdyn_responseoutcome_Account");
				this.SetRelatedEntity<Azuro.Crm.Entities.Account>("msdyn_account_msdyn_responseoutcome_Account", null, value);
				this.OnPropertyChanged("msdyn_account_msdyn_responseoutcome_Account");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_contact_msdyn_responseoutcome_Contact
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_contact")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_contact_msdyn_responseoutcome_Contact")]
		public Azuro.Crm.Entities.Contact msdyn_contact_msdyn_responseoutcome_Contact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.Contact>("msdyn_contact_msdyn_responseoutcome_Contact", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_contact_msdyn_responseoutcome_Contact");
				this.SetRelatedEntity<Azuro.Crm.Entities.Contact>("msdyn_contact_msdyn_responseoutcome_Contact", null, value);
				this.OnPropertyChanged("msdyn_contact_msdyn_responseoutcome_Contact");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_lead_msdyn_responseoutcome_Lead
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_lead")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_lead_msdyn_responseoutcome_Lead")]
		public Azuro.Crm.Entities.Lead msdyn_lead_msdyn_responseoutcome_Lead
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.Lead>("msdyn_lead_msdyn_responseoutcome_Lead", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_lead_msdyn_responseoutcome_Lead");
				this.SetRelatedEntity<Azuro.Crm.Entities.Lead>("msdyn_lead_msdyn_responseoutcome_Lead", null, value);
				this.OnPropertyChanged("msdyn_lead_msdyn_responseoutcome_Lead");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_triggeringresponseactionrule")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule")]
		public Azuro.Crm.Entities.msdyn_responseaction msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.msdyn_responseaction>("msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule");
				this.SetRelatedEntity<Azuro.Crm.Entities.msdyn_responseaction>("msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule", null, value);
				this.OnPropertyChanged("msdyn_msdyn_responseaction_msdyn_responseoutcome_TriggeringResponseActionRule");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_survey_msdyn_responseoutcome_SurveyId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_surveyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_survey_msdyn_responseoutcome_SurveyId")]
		public Azuro.Crm.Entities.msdyn_survey msdyn_msdyn_survey_msdyn_responseoutcome_SurveyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.msdyn_survey>("msdyn_msdyn_survey_msdyn_responseoutcome_SurveyId", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_survey_msdyn_responseoutcome_SurveyId");
				this.SetRelatedEntity<Azuro.Crm.Entities.msdyn_survey>("msdyn_msdyn_survey_msdyn_responseoutcome_SurveyId", null, value);
				this.OnPropertyChanged("msdyn_msdyn_survey_msdyn_responseoutcome_SurveyId");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_surveyinvite_msdyn_responseoutcome_Invitation
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_invitation")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_surveyinvite_msdyn_responseoutcome_Invitation")]
		public Azuro.Crm.Entities.msdyn_surveyinvite msdyn_msdyn_surveyinvite_msdyn_responseoutcome_Invitation
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.msdyn_surveyinvite>("msdyn_msdyn_surveyinvite_msdyn_responseoutcome_Invitation", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_surveyinvite_msdyn_responseoutcome_Invitation");
				this.SetRelatedEntity<Azuro.Crm.Entities.msdyn_surveyinvite>("msdyn_msdyn_surveyinvite_msdyn_responseoutcome_Invitation", null, value);
				this.OnPropertyChanged("msdyn_msdyn_surveyinvite_msdyn_responseoutcome_Invitation");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_surveyresponse_SurveyResponse
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_surveyresponse")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_surveyresponse_SurveyResponse")]
		public Azuro.Crm.Entities.msdyn_surveyresponse msdyn_surveyresponse_SurveyResponse
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.msdyn_surveyresponse>("msdyn_surveyresponse_SurveyResponse", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_surveyresponse_SurveyResponse");
				this.SetRelatedEntity<Azuro.Crm.Entities.msdyn_surveyresponse>("msdyn_surveyresponse_SurveyResponse", null, value);
				this.OnPropertyChanged("msdyn_surveyresponse_SurveyResponse");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public msdyn_responseoutcome(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["msdyn_responseoutcomeid"] = base.Id;
                        break;
                    case "msdyn_responseoutcomeid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_responseoutcometype")]
		public virtual msdyn_SurveyActionType? msdyn_responseoutcomeTypeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_SurveyActionType?)(EntityOptionSetEnum.GetEnum(this, "msdyn_responseoutcometype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				msdyn_responseoutcomeType = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual msdyn_responseoutcome_StatusCode? StatusCodeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((msdyn_responseoutcome_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				StatusCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}