//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azuro.Crm.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public enum cdi_webcontentState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("cdi_webcontent")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public partial class cdi_webcontent : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string cdi_automationid = "cdi_automationid";
			public const string cdi_CampaignId = "cdi_campaignid";
			public const string cdi_CategoryId = "cdi_categoryid";
			public const string cdi_DomainId = "cdi_domainid";
			public const string cdi_editortype = "cdi_editortype";
			public const string cdi_EmailNotificationAddress = "cdi_emailnotificationaddress";
			public const string cdi_EmailTemplateId = "cdi_emailtemplateid";
			public const string cdi_name = "cdi_name";
			public const string cdi_ProfileId = "cdi_profileid";
			public const string cdi_Score = "cdi_score";
			public const string cdi_Subject = "cdi_subject";
			public const string cdi_Type = "cdi_type";
			public const string cdi_VisitorEntity = "cdi_visitorentity";
			public const string cdi_webcontentId = "cdi_webcontentid";
			public const string Id = "cdi_webcontentid";
			public const string cdi_webresponsive = "cdi_webresponsive";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string cdi_automation_cdi_webcontent = "cdi_automation_cdi_webcontent";
			public const string cdi_campaign_cdi_webcontent = "cdi_campaign_cdi_webcontent";
			public const string cdi_category_cdi_webcontent = "cdi_category_cdi_webcontent";
			public const string cdi_domain_cdi_webcontent = "cdi_domain_cdi_webcontent";
			public const string cdi_emailtemplate_cdi_webcontent = "cdi_emailtemplate_cdi_webcontent";
			public const string cdi_profile_cdi_webcontent = "cdi_profile_cdi_webcontent";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public cdi_webcontent() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "cdi_webcontent";
		
		public const string PrimaryIdAttribute = "cdi_webcontentid";
		
		public const string PrimaryNameAttribute = "cdi_name";
		
		public const int EntityTypeCode = 10078;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier for Campaign Automation associated with Web Content.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_automationid")]
		public Microsoft.Xrm.Sdk.EntityReference cdi_automationid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cdi_automationid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_automationid");
				this.SetAttributeValue("cdi_automationid", value);
				this.OnPropertyChanged("cdi_automationid");
			}
		}
		
		/// <summary>
		/// Unique identifier for Campaign associated with Web Content.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_campaignid")]
		public Microsoft.Xrm.Sdk.EntityReference cdi_CampaignId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cdi_campaignid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_CampaignId");
				this.SetAttributeValue("cdi_campaignid", value);
				this.OnPropertyChanged("cdi_CampaignId");
			}
		}
		
		/// <summary>
		/// Unique identifier for Category associated with Web Content.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_categoryid")]
		public Microsoft.Xrm.Sdk.EntityReference cdi_CategoryId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cdi_categoryid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_CategoryId");
				this.SetAttributeValue("cdi_categoryid", value);
				this.OnPropertyChanged("cdi_CategoryId");
			}
		}
		
		/// <summary>
		/// Unique identifier for Domain associated with Web Content.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_domainid")]
		public Microsoft.Xrm.Sdk.EntityReference cdi_DomainId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cdi_domainid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_DomainId");
				this.SetAttributeValue("cdi_domainid", value);
				this.OnPropertyChanged("cdi_DomainId");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_editortype")]
		public Microsoft.Xrm.Sdk.OptionSetValue cdi_editortype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("cdi_editortype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_editortype");
				this.SetAttributeValue("cdi_editortype", value);
				this.OnPropertyChanged("cdi_editortype");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_emailnotificationaddress")]
		public string cdi_EmailNotificationAddress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("cdi_emailnotificationaddress");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_EmailNotificationAddress");
				this.SetAttributeValue("cdi_emailnotificationaddress", value);
				this.OnPropertyChanged("cdi_EmailNotificationAddress");
			}
		}
		
		/// <summary>
		/// Unique identifier for Email Template associated with Web Content.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_emailtemplateid")]
		public Microsoft.Xrm.Sdk.EntityReference cdi_EmailTemplateId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cdi_emailtemplateid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_EmailTemplateId");
				this.SetAttributeValue("cdi_emailtemplateid", value);
				this.OnPropertyChanged("cdi_EmailTemplateId");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_name")]
		public string cdi_name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("cdi_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_name");
				this.SetAttributeValue("cdi_name", value);
				this.OnPropertyChanged("cdi_name");
			}
		}
		
		/// <summary>
		/// Unique identifier for Profile associated with Web Content.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_profileid")]
		public Microsoft.Xrm.Sdk.EntityReference cdi_ProfileId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("cdi_profileid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_ProfileId");
				this.SetAttributeValue("cdi_profileid", value);
				this.OnPropertyChanged("cdi_ProfileId");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_score")]
		public System.Nullable<int> cdi_Score
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("cdi_score");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_Score");
				this.SetAttributeValue("cdi_score", value);
				this.OnPropertyChanged("cdi_Score");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_subject")]
		public string cdi_Subject
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("cdi_subject");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_Subject");
				this.SetAttributeValue("cdi_subject", value);
				this.OnPropertyChanged("cdi_Subject");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_type")]
		public Microsoft.Xrm.Sdk.OptionSetValue cdi_Type
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("cdi_type");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_Type");
				this.SetAttributeValue("cdi_type", value);
				this.OnPropertyChanged("cdi_Type");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_visitorentity")]
		public Microsoft.Xrm.Sdk.OptionSetValue cdi_VisitorEntity
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("cdi_visitorentity");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_VisitorEntity");
				this.SetAttributeValue("cdi_visitorentity", value);
				this.OnPropertyChanged("cdi_VisitorEntity");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_webcontentid")]
		public System.Nullable<System.Guid> cdi_webcontentId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("cdi_webcontentid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_webcontentId");
				this.SetAttributeValue("cdi_webcontentid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("cdi_webcontentId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_webcontentid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.cdi_webcontentId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_webresponsive")]
		public System.Nullable<bool> cdi_webresponsive
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("cdi_webresponsive");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_webresponsive");
				this.SetAttributeValue("cdi_webresponsive", value);
				this.OnPropertyChanged("cdi_webresponsive");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Web Content
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Azuro.Crm.Entities.cdi_webcontentState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Azuro.Crm.Entities.cdi_webcontentState)(System.Enum.ToObject(typeof(Azuro.Crm.Entities.cdi_webcontentState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Web Content
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N cdi_webcontent_ActivityPointers
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cdi_webcontent_ActivityPointers")]
		public System.Collections.Generic.IEnumerable<Azuro.Crm.Entities.ActivityPointer> cdi_webcontent_ActivityPointers
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Azuro.Crm.Entities.ActivityPointer>("cdi_webcontent_ActivityPointers", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_webcontent_ActivityPointers");
				this.SetRelatedEntities<Azuro.Crm.Entities.ActivityPointer>("cdi_webcontent_ActivityPointers", null, value);
				this.OnPropertyChanged("cdi_webcontent_ActivityPointers");
			}
		}
		
		/// <summary>
		/// 1:N cdi_webcontent_cdi_pageview
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cdi_webcontent_cdi_pageview")]
		public System.Collections.Generic.IEnumerable<Azuro.Crm.Entities.cdi_pageview> cdi_webcontent_cdi_pageview
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Azuro.Crm.Entities.cdi_pageview>("cdi_webcontent_cdi_pageview", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_webcontent_cdi_pageview");
				this.SetRelatedEntities<Azuro.Crm.Entities.cdi_pageview>("cdi_webcontent_cdi_pageview", null, value);
				this.OnPropertyChanged("cdi_webcontent_cdi_pageview");
			}
		}
		
		/// <summary>
		/// 1:N cdi_webcontent_cdi_postedform
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cdi_webcontent_cdi_postedform")]
		public System.Collections.Generic.IEnumerable<Azuro.Crm.Entities.cdi_postedform> cdi_webcontent_cdi_postedform
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Azuro.Crm.Entities.cdi_postedform>("cdi_webcontent_cdi_postedform", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_webcontent_cdi_postedform");
				this.SetRelatedEntities<Azuro.Crm.Entities.cdi_postedform>("cdi_webcontent_cdi_postedform", null, value);
				this.OnPropertyChanged("cdi_webcontent_cdi_postedform");
			}
		}
		
		/// <summary>
		/// 1:N cdi_webcontent_cdi_postedsubscription
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cdi_webcontent_cdi_postedsubscription")]
		public System.Collections.Generic.IEnumerable<Azuro.Crm.Entities.cdi_postedsubscription> cdi_webcontent_cdi_postedsubscription
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Azuro.Crm.Entities.cdi_postedsubscription>("cdi_webcontent_cdi_postedsubscription", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_webcontent_cdi_postedsubscription");
				this.SetRelatedEntities<Azuro.Crm.Entities.cdi_postedsubscription>("cdi_webcontent_cdi_postedsubscription", null, value);
				this.OnPropertyChanged("cdi_webcontent_cdi_postedsubscription");
			}
		}
		
		/// <summary>
		/// 1:N cdi_webcontent_cdi_postedsurvey
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cdi_webcontent_cdi_postedsurvey")]
		public System.Collections.Generic.IEnumerable<Azuro.Crm.Entities.cdi_postedsurvey> cdi_webcontent_cdi_postedsurvey
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Azuro.Crm.Entities.cdi_postedsurvey>("cdi_webcontent_cdi_postedsurvey", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_webcontent_cdi_postedsurvey");
				this.SetRelatedEntities<Azuro.Crm.Entities.cdi_postedsurvey>("cdi_webcontent_cdi_postedsurvey", null, value);
				this.OnPropertyChanged("cdi_webcontent_cdi_postedsurvey");
			}
		}
		
		/// <summary>
		/// 1:N cdi_webcontent_cdi_txtmessages
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cdi_webcontent_cdi_txtmessages")]
		public System.Collections.Generic.IEnumerable<Azuro.Crm.Entities.cdi_txtmessage> cdi_webcontent_cdi_txtmessages
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Azuro.Crm.Entities.cdi_txtmessage>("cdi_webcontent_cdi_txtmessages", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_webcontent_cdi_txtmessages");
				this.SetRelatedEntities<Azuro.Crm.Entities.cdi_txtmessage>("cdi_webcontent_cdi_txtmessages", null, value);
				this.OnPropertyChanged("cdi_webcontent_cdi_txtmessages");
			}
		}
		
		/// <summary>
		/// 1:N cdi_webcontent_msdyn_surveyinvites
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cdi_webcontent_msdyn_surveyinvites")]
		public System.Collections.Generic.IEnumerable<Azuro.Crm.Entities.msdyn_surveyinvite> cdi_webcontent_msdyn_surveyinvites
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Azuro.Crm.Entities.msdyn_surveyinvite>("cdi_webcontent_msdyn_surveyinvites", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_webcontent_msdyn_surveyinvites");
				this.SetRelatedEntities<Azuro.Crm.Entities.msdyn_surveyinvite>("cdi_webcontent_msdyn_surveyinvites", null, value);
				this.OnPropertyChanged("cdi_webcontent_msdyn_surveyinvites");
			}
		}
		
		/// <summary>
		/// N:1 cdi_automation_cdi_webcontent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_automationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cdi_automation_cdi_webcontent")]
		public Azuro.Crm.Entities.cdi_automation cdi_automation_cdi_webcontent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.cdi_automation>("cdi_automation_cdi_webcontent", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_automation_cdi_webcontent");
				this.SetRelatedEntity<Azuro.Crm.Entities.cdi_automation>("cdi_automation_cdi_webcontent", null, value);
				this.OnPropertyChanged("cdi_automation_cdi_webcontent");
			}
		}
		
		/// <summary>
		/// N:1 cdi_campaign_cdi_webcontent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_campaignid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cdi_campaign_cdi_webcontent")]
		public Azuro.Crm.Entities.Campaign cdi_campaign_cdi_webcontent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.Campaign>("cdi_campaign_cdi_webcontent", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_campaign_cdi_webcontent");
				this.SetRelatedEntity<Azuro.Crm.Entities.Campaign>("cdi_campaign_cdi_webcontent", null, value);
				this.OnPropertyChanged("cdi_campaign_cdi_webcontent");
			}
		}
		
		/// <summary>
		/// N:1 cdi_category_cdi_webcontent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_categoryid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cdi_category_cdi_webcontent")]
		public Azuro.Crm.Entities.cdi_category cdi_category_cdi_webcontent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.cdi_category>("cdi_category_cdi_webcontent", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_category_cdi_webcontent");
				this.SetRelatedEntity<Azuro.Crm.Entities.cdi_category>("cdi_category_cdi_webcontent", null, value);
				this.OnPropertyChanged("cdi_category_cdi_webcontent");
			}
		}
		
		/// <summary>
		/// N:1 cdi_domain_cdi_webcontent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_domainid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cdi_domain_cdi_webcontent")]
		public Azuro.Crm.Entities.cdi_domain cdi_domain_cdi_webcontent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.cdi_domain>("cdi_domain_cdi_webcontent", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_domain_cdi_webcontent");
				this.SetRelatedEntity<Azuro.Crm.Entities.cdi_domain>("cdi_domain_cdi_webcontent", null, value);
				this.OnPropertyChanged("cdi_domain_cdi_webcontent");
			}
		}
		
		/// <summary>
		/// N:1 cdi_emailtemplate_cdi_webcontent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_emailtemplateid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cdi_emailtemplate_cdi_webcontent")]
		public Azuro.Crm.Entities.cdi_emailtemplate cdi_emailtemplate_cdi_webcontent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.cdi_emailtemplate>("cdi_emailtemplate_cdi_webcontent", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_emailtemplate_cdi_webcontent");
				this.SetRelatedEntity<Azuro.Crm.Entities.cdi_emailtemplate>("cdi_emailtemplate_cdi_webcontent", null, value);
				this.OnPropertyChanged("cdi_emailtemplate_cdi_webcontent");
			}
		}
		
		/// <summary>
		/// N:1 cdi_profile_cdi_webcontent
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_profileid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("cdi_profile_cdi_webcontent")]
		public Azuro.Crm.Entities.cdi_profile cdi_profile_cdi_webcontent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Azuro.Crm.Entities.cdi_profile>("cdi_profile_cdi_webcontent", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("cdi_profile_cdi_webcontent");
				this.SetRelatedEntity<Azuro.Crm.Entities.cdi_profile>("cdi_profile_cdi_webcontent", null, value);
				this.OnPropertyChanged("cdi_profile_cdi_webcontent");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public cdi_webcontent(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["cdi_webcontentid"] = base.Id;
                        break;
                    case "cdi_webcontentid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_editortype")]
		public virtual cdi_webcontent_cdi_editortype? cdi_editortypeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((cdi_webcontent_cdi_editortype?)(EntityOptionSetEnum.GetEnum(this, "cdi_editortype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				cdi_editortype = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_type")]
		public virtual cdi_webcontent_cdi_Type? cdi_TypeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((cdi_webcontent_cdi_Type?)(EntityOptionSetEnum.GetEnum(this, "cdi_type")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				cdi_Type = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cdi_visitorentity")]
		public virtual cdi_webcontent_cdi_VisitorEntity? cdi_VisitorEntityEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((cdi_webcontent_cdi_VisitorEntity?)(EntityOptionSetEnum.GetEnum(this, "cdi_visitorentity")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				cdi_VisitorEntity = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual cdi_webcontent_StatusCode? StatusCodeEnum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((cdi_webcontent_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				StatusCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}